### ISSUE TITLE
Неверный путь картинки в админке

### ISSUE THREAD

**Issue by instocky** [lee-to/laravel-admin#1]
адмика встала
но картинка у юзера [не отображается ](https://prnt.sc/1hjxqgx) 
[здесь](https://prnt.sc/1hjyfgn) такой же баг

**Comment by lee-to** [comment]
скриншоты отдают 404, попробуйте изменить config/filesystem.php на public по умолчанию и убедиться что стоит symbolic link на Storage

**Comment by lee-to** [comment]
Перепровевил, ошибка возникает если нет символической ссылки php artisan storage:link
